"""empty message

Revision ID: dd1ef82919ab
Revises: 772332214331
Create Date: 2021-03-17 13:25:28.445099

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'dd1ef82919ab'
down_revision = '772332214331'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('hangers', sa.Column('name', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('hangers', 'name')
    # ### end Alembic commands ###
